### ISSUE TITLE
Mavericks: WebExtensions Process starts using 100% CPU, something related to Garbage Collection?

### ISSUE THREAD

**Issue by Wowfunhappy** [i3roly/firefox-dynasty#15]
Periodically when I test Firefox Dynasty on Mavericks, the WebExtensions process will start burning 100% CPU. (Note that I have no extensions installed,so I'm not even sure what this process is doing.)

Unlike when Firefox as a whole locks up with a beachball, I am able to use the Profiler on the  WebExtensions process. Two profiles are attached which can be uploaded to profiler.firefox.com.

[Firefox 2024-10-12 13.40 profile.json.gz](https://github.com/user-attachments/files/17350950/Firefox.2024-10-12.13.40.profile.json.gz)
[Firefox 2024-10-12 13.48 profile.json.gz](https://github.com/user-attachments/files/17350951/Firefox.2024-10-12.13.48.profile.json.gz)

From my naïve read, it looks like the problem is related to garbage collection. The function `mozilla::detail::ConditionVariableImpl::wait_for(mozilla::detail::MutexImpl&, mozilla::BaseTimeDuration<mozilla::TimeDurationValueCalculator> const&)` is implicated far down the call graph.

**Comment by i3roly** [comment]
that's 'just' blocking.

you are right the issue exists though. it's more pronounced in 10.7. i haven't encountered it in 10.8, not from what i can recall anyways.

i did encounter it all afternoon during this discussion, so i am aware it must have existed from last week to about half an hour ago, when the most recent build was posted, since those releases removed access to urandom.

it's also possible (maybe likely) you will still it, but i cannot use the profiles above as fresh evidence for obvious reasons.

**Comment by Wowfunhappy** [comment]
If the problem is still here, I can't trigger it!
